workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/main/output/plex-media-server-spec-dereferenced.yaml
        registry:
            location: registry.speakeasyapi.dev/lukehagar/lukehagar/my-source
targets:
    plexcsharp:
        target: csharp
        source: my-source
