workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plex-api:
        inputs:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api:main
targets:
    plexcsharp:
        target: csharp
        source: my-source
